apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: postgresql.database.platform.io
  labels:
    provider: kubernetes
    database: postgresql
spec:
  compositeTypeRef:
    apiVersion: database.platform.io/v1alpha1
    kind: XPostgreSQLInstance

  mode: Pipeline

  pipeline:
    - step: patch-and-transform
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:

          # ----------------------------
          # PostgreSQL Deployment
          # ----------------------------
          - name: postgresql-deployment
            base:
              apiVersion: kubernetes.crossplane.io/v1alpha1
              kind: Object
              spec:
                providerConfigRef:
                  name: kubernetes-provider
                forProvider:
                  manifest:
                    apiVersion: apps/v1
                    kind: Deployment
                    metadata:
                      name: postgresql
                    spec:
                      replicas: 1
                      selector:
                        matchLabels:
                          app: postgresql
                      template:
                        metadata:
                          labels:
                            app: postgresql
                        spec:
                          containers:
                            - name: postgresql
                              image: postgres:15-alpine
                              ports:
                                - containerPort: 5432
                              env:
                                - name: POSTGRES_DB
                                  value: appdb
                                - name: POSTGRES_USER
                                  value: appuser
                                - name: POSTGRES_PASSWORD
                                  value: changeme123
                              resources:
                                requests:
                                  cpu: 100m
                                  memory: 256Mi
                                limits:
                                  cpu: 500m
                                  memory: 512Mi
                              volumeMounts:
                                - name: data
                                  mountPath: /var/lib/postgresql/data
                          volumes:
                            - name: data
                              emptyDir: {}

            patches:
              - fromFieldPath: metadata.name
                toFieldPath: spec.forProvider.manifest.metadata.name

              - fromFieldPath: metadata.labels['crossplane.io/claim-namespace']
                toFieldPath: spec.forProvider.manifest.metadata.namespace

              - fromFieldPath: spec.parameters.size
                toFieldPath: spec.forProvider.manifest.spec.template.spec.containers[0].resources.requests.memory
                transforms:
                  - type: map
                    map:
                      small: "256Mi"
                      medium: "512Mi"
                      large: "1Gi"

          # ----------------------------
          # PostgreSQL Service
          # ----------------------------
          - name: postgresql-service
            base:
              apiVersion: kubernetes.crossplane.io/v1alpha1
              kind: Object
              spec:
                providerConfigRef:
                  name: kubernetes-provider
                forProvider:
                  manifest:
                    apiVersion: v1
                    kind: Service
                    metadata:
                      name: postgresql
                    spec:
                      selector:
                        app: postgresql
                      ports:
                        - port: 5432
                          targetPort: 5432
                      type: ClusterIP

            patches:
              - fromFieldPath: metadata.name
                toFieldPath: spec.forProvider.manifest.metadata.name

              - fromFieldPath: metadata.labels['crossplane.io/claim-namespace']
                toFieldPath: spec.forProvider.manifest.metadata.namespace

          # ----------------------------
          # Connection Secret
          # ----------------------------
          - name: connection-secret
            base:
              apiVersion: kubernetes.crossplane.io/v1alpha1
              kind: Object
              spec:
                providerConfigRef:
                  name: kubernetes-provider
                forProvider:
                  manifest:
                    apiVersion: v1
                    kind: Secret
                    metadata:
                      name: postgresql-credentials
                    type: Opaque
                    stringData:
                      host: postgresql
                      port: "5432"
                      database: appdb
                      username: appuser
                      password: changeme123

            patches:
              # Secret name = <claim-name>-credentials
              - fromFieldPath: metadata.name
                toFieldPath: spec.forProvider.manifest.metadata.name
                transforms:
                  - type: string
                    string:
                      type: Format
                      fmt: "%s-credentials"

              - fromFieldPath: metadata.labels['crossplane.io/claim-namespace']
                toFieldPath: spec.forProvider.manifest.metadata.namespace
