apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-1-metrics
  namespace: nodejs-app-1
  labels:
    app: nodejs-app-1
    metrics: "true"
spec:
  selector:
    app: nodejs-app-1
  ports:
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nodejs-app-1
  namespace: nodejs-app-1
  labels:
    app: nodejs-app-1
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: nodejs-app-1
      metrics: "true"
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: nodejs-app-1
  namespace: nodejs-app-1
  labels:
    app: nodejs-app-1
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: nodejs-app-1
  podMetricsEndpoints:
  - port: metrics
    interval: 30s
    path: /metrics
