apiVersion: v1
kind: Service
metadata:
  name: demo-service-6-metrics
  namespace: demo-service-6
  labels:
    app: demo-service-6
    metrics: "true"
spec:
  selector:
    app: demo-service-6
  ports:
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-service-6
  namespace: demo-service-6
  labels:
    app: demo-service-6
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: demo-service-6
      metrics: "true"
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: demo-service-6
  namespace: demo-service-6
  labels:
    app: demo-service-6
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: demo-service-6
  podMetricsEndpoints:
  - port: metrics
    interval: 30s
    path: /metrics
